server {
    listen 80;
    listen [::]:80;
    server_name carepyre.org www.carepyre.org;

    root /var/www/carepyre;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    location /.well-known/acme-challenge/ {
        root /var/www/html;
    }
}
